# Generated by Django 3.0.8 on 2022-04-30 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('password', models.CharField(max_length=20, verbose_name='PASSWORD')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='계정 생성일')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=32, verbose_name='이름')),
            ],
            options={
                'verbose_name': '유저',
                'verbose_name_plural': '유저',
                'db_table': 'Account',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
