# Generated by Django 3.0.8 on 2022-04-30 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0003_auto_20220430_2325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drama',
            options={'verbose_name': 'NAME', 'verbose_name_plural': 'NAME'},
        ),
        migrations.AlterModelTable(
            name='drama',
            table='DRAMA',
        ),
    ]
