# Generated by Django 3.0.8 on 2022-04-30 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0004_auto_20220430_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drama',
            options={'verbose_name': 'DRAMA', 'verbose_name_plural': 'DRAMA'},
        ),
    ]
